# Generated by Django 2.1.5 on 2019-02-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=200, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Artifact')),
            ],
        ),
    ]
