# Generated by Django 2.1.5 on 2019-02-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0002_artifact_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Artifact'),
        ),
    ]
