# Generated by Django 2.1.5 on 2019-03-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctionapp', '0003_auto_20190221_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='profile/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('a', 'Admin'), ('m', 'Moderator'), ('s', 'Seller'), ('b', 'Buyer')], max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
