# Generated by Django 2.1.5 on 2019-03-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0007_auto_20190303_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('a', 'Admin'), ('m', 'Moderator'), ('s', 'Seller'), ('b', 'Buyer')], default='a', max_length=1),
        ),
    ]
