# Generated by Django 2.1.5 on 2019-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0009_auto_20190303_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('a', 'Admin'), ('m', 'Moderator'), ('s', 'Seller'), ('b', 'Buyer')], default='b', max_length=1, null=True),
        ),
    ]
