# Generated by Django 2.1.5 on 2019-03-06 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0010_auto_20190303_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('S', 'Seller'), ('B', 'Buyer')], default='B', max_length=1, null=True),
        ),
    ]
