# Generated by Django 2.1.5 on 2019-03-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0011_auto_20190306_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidder',
        ),
    ]
