# Generated by Django 2.1.5 on 2019-03-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0014_auto_20190322_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
